#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Esri.ArcGISRuntime.OpenSourceApps.MapsApp.Android.Resource", IsApplication=true)]

namespace Esri.ArcGISRuntime.OpenSourceApps.MapsApp.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int BearLeft = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int BearRight = 2130771969;
			
			// aapt resource value: 0x7F010018
			public const int choosebasemap = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int chooseusermap = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int close = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int compass = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int currentlocation = 2130771996;
			
			// aapt resource value: 0x7F010002
			public const int Depart = 2130771970;
			
			// aapt resource value: 0x7F01001D
			public const int directionmaneuvers = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int directions = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int endpin = 2130771999;
			
			// aapt resource value: 0x7F010003
			public const int ForkCenter = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ForkLeft = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ForkRight = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int HighwayChange = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int HighwayExit = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int HighwayMerge = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int Icon = 2130771977;
			
			// aapt resource value: 0x7F010020
			public const int menu = 2130772000;
			
			// aapt resource value: 0x7F01000A
			public const int RampLeft = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int RampRight = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int Roundabout = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int SharpLeft = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int SharpRight = 2130771982;
			
			// aapt resource value: 0x7F010021
			public const int sign_in_out = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int startpin = 2130772002;
			
			// aapt resource value: 0x7F01000F
			public const int Stop = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int Straight = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int TurnLeft = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int TurnLeftLeft = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int TurnLeftRight = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int TurnRight = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int TurnRightLeft = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int TurnRightRight = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int UTurn = 2130771991;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int sliding_tabs = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int toolbar = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Tabbar = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int AppCompatDialogStyle = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MainTheme = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MainTheme_Base = 2130968578;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
